### ISSUE TITLE
published as "preeti" on npm

### ISSUE THREAD

**Issue by mapmeld** [sapradhan/nep-ttf2utf#8]
hey,
I've reworked the library a bit so it works as a module for NodeJS.  You can see code and one test here: https://github.com/mapmeld/preeti

```bash
npm install preeti
```

```javascript
preeti = require('preeti');
preeti('sf7df08"');
> 'काठमाण्डू'
```

namaste!

**Comment by sapradhan** [comment]
this is great, thanks. Please find more test vectors at https://github.com/sapradhan/nep-ttf2utf/tree/master/test/vectors
I looked into the code, looks good. let me know if I can help in any way. 

धन्यवाद

**Comment by mapmeld** [comment]
I added in these test vectors and the only failing one is this in PCS Nepali:

```emfj|mL --> झाक्री```

instead I am getting back ```झmाव्री```

This one does work:

```emfs|L --> झाक्री```

**Comment by sapradhan** [comment]
that is a very rare usage. I dont think its supported right now, thats probably why this case is not there in other fonts. Will see if there is something I can do about that. Please remove this one for now.

**Comment by mapmeld** [comment]
ok thanks! published with new tests
